export * from './endsWith'
export * from './includes'
export * from './lowerCase'
export * from './replace'
export * from './split'
export * from './startsWith'
export * from './trim'
export * from './upperCase'
